### ISSUE TITLE
Fix design of FAQ app

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/faq#71]
- [ ] change font-weight in navigation
- [ ]  add class .hide to sub-navigation
- [ ] add "docs" to meta-navigation
- [ ] do not change input background-color on focus
- [ ] increase the line-height of list
- [ ] redesign buttons

**Comment by boennemann** [comment]
@zoepage Is the list still up to date? Seems like most of it is done, even though I can't say for sure right now.
